defaults:
  - hydra: local
  - dataset: cingulate_HCP_full_Flanker_AgeAdj_shuffled
  - model: SimCLR_supervised
  - mode: regresser
  - augmentations: foldlabel
  - backbone: ConvNet
  - platform: cuda_not_brainvisa
  - trainer: default
  - classifier: svm
  - embeddings: embeddings
  - override hydra/job_logging: custom